In [34]:
import numpy as np
import pandas as pd

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.rand(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
        
    # Forward pass
    def forward(self, inputs):
        # Calculate output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases

In [40]:
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

# Create dataset using spiral_data
# - samples(2 features): number of batches/samples to generate for EACH class
# - classes(1 feature): number of unique classes - 1D 
# Example: samples=1,classes=1 --> X=[[1.1, 1.2]], y=[0] 
X, y = spiral_data(samples=100, classes=3)

# Create Dense Layer with 2 input features and 3 output values
# - n_inputs must match number of features per batch being inputted
# - n_neurons can be however many neurons you want the inputs to be fed out to
layer1 = Layer_Dense(2,3)

# Perform a forward feed of our training data through this layer
layer1.forward(X)

# Let's see output of the first few samples:
print(layer1.output[:5])
print(layer1.output.shape)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.97437393e-05 3.68895635e-05 8.37819971e-05]
 [1.46999708e-04 9.15808050e-05 1.40212578e-04]
 [2.07372344e-04 1.30936343e-04 5.65641167e-05]
 [2.86790368e-04 1.80765084e-04 1.03854705e-04]]
(300, 3)


In [42]:
# Let's create another layer to then connect to Layer 1
# - n_inputs for Layer 2 MUST BE EQUAL to the number of neurons Layer 1 outputted
layer2 = Layer_Dense(3, 4)

# Pass in the outputs from layer 1
layer2.forward(layer1.output)

print(layer2.output[:5])
print(layer2.output.shape)

[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [3.8623335e-07 5.0935955e-07 5.0201709e-07 1.2278412e-07]
 [8.0463690e-07 1.0898336e-06 1.1493601e-06 2.9622544e-07]
 [8.2301898e-07 1.1873118e-06 1.4374938e-06 4.0527806e-07]
 [1.1948430e-06 1.7055517e-06 2.0213868e-06 5.6277628e-07]]
(300, 4)
